version: '2'

volumes:
    pgdata:
    pgbackup:

services:
    postgres:
        container_name: livingarchives-postgres
        build: ./compose/postgres
        volumes:
            - pgdata:/var/lib/postgresql/data
            - pgbackup:/backups
        env_file: .env

    node:
        container_name: livingarchives-node
        build:
            context: .
            dockerfile: ./compose/node/Dockerfile
        env_file: .env
        depends_on:
            - postgres
        volumes:
            - ./node:/opt/node:rw

    nginx:
        container_name: livingarchives-nginx
        build:
            context: .
            dockerfile: ./compose/nginx/Dockerfile
        depends_on:
            - node
        volumes_from:
            - node:rw
        ports:
            - "80:80"
            - "443:443"
            - "3000:3000" # api.livingarchives.org
            - "3001:3001" # alberta.livingarchives.org
            - "3002:3002" # bitterandsweet.livingarchives.org
            - "8000:8000" # livingarchives.org
            - "8001:8001" # skybox.livingarchives.org
            - "8002:8002" # affexity.livingarchives.org
            - "8003:8003" # somatic.livingarchives.org
        volumes:
            - ./sites:/opt/sites:rw
    sftp:
        image: atmoz/sftp
        container_name: livingarchives-sftp
        volumes:
            - ./sftp-users.conf:/etc/sftp-users.conf:ro
            - ./sites/affexity.livingarchives.org:/home/livingarchives/affexity.livingarchives.org
        ports:
            - "2222:22"
